### ISSUE TITLE
Does not work when using with Datadog extension

### ISSUE THREAD

**Issue by gabrielcolson** [ServerlessLife/serverless-spy#7]
When I add the ServerlessSpy construct to a stack that contains the call to `datadog.addLambdaFunctions([<LAMBDA_FUNCTIONS>])` from `datadog-cdk-constructs-v2`, I get the following error when I try to execute the lambda function:

```json
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'handler'\nRequire stack:\n- /opt/nodejs/node_modules/interceptor.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'handler'",
        "Require stack:",
        "- /opt/nodejs/node_modules/interceptor.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (/opt/nodejs/node_modules/interceptor.js:26578:13)",
        "    at load (/opt/nodejs/node_modules/interceptor.js:26595:19)",
        "    at getOriginalHandler (/opt/nodejs/node_modules/interceptor.js:26902:10)",
        "    at Runtime.handler (/opt/nodejs/node_modules/interceptor.js:26791:27)",
        "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1089:29)"
    ]
}
```

I fixed it by removing the datadog extension when I want to include the ServerlessSpy construct event though it is not optimal

**Comment by ServerlessLife** [comment]
Hey Gabriel,

Thank you for reporting the issue. Unfortunately, the problem would be really hard to solve. 

SperverlessSpy, as well as DataDog (and similar extensions), use an extension of type "internal". And there could be only one internal extension because, essentially, it wraps your code and tries to spy/track what it is doing. Maybe there is a hack that I am not aware of to make this work.

The only way to resposlve the issue, as you already figure out, is to remove any other internal extension. You can do that just for stages/environments in which you would like to use ServerlessSpy. You would not use ServerlessSpy in the production environment, and you can use DataDog there.

If you have any other questions, please do not hesitate to contact me:
https://www.linkedin.com/in/marko-serverlesslife/

Am I also very interested how is your experience with the ServerlessSpy.

**Comment by gabrielcolson** [comment]
Hey,

Thank you for your response. I didn't think it would be that hard but the workaround is fine for now.

Thanks for making SeverlessSpy, it looks great! We hope to replace our internal equivalent of `sls-test-tools` with it.

I will let you know if I come across anything else.
